version: "3.1"

services:
    mongodb:
        image: "mongo:4.1"
        container_name: mongo
        restart: always
        environment:
            - "MONGO_INITDB_ROOT_USERNAME=root"
            - "MONGO_INITDB_ROOT_PASSWORD=mongodb"
        volumes:
            - "mongodb_data:/data/db"
            - "/etc/localtime:/etc/localtime"
        ports:
            - 27017:27017

    mongo-express:
        image: "mongo-express:0.49"
        container_name: "mongo-express"
        restart: "always"
        environment:
            - "ME_CONFIG_MONGODB_ADMINUSERNAME=root"
            - "ME_CONFIG_MONGODB_ADMINPASSWORD=mongodb"
        ports:
            - "8081:8081"
        depends_on:
            - mongodb

    redis:
        image: redis:alpine
        container_name: "redis"
        restart: always
        volumes:
            - "redis_data:/data"
        ports:
            - "6379:6379"

    mysql:
        image: "mysql:5.7"
        container_name: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        restart: "always"
        environment:
            MYSQL_ROOT_PASSWORD: 123qwe
            MYSQL_DATABASE: todos
            MYSQL_USER: liuzt
            MYSQL_PASSWORD: 123qwe
        ports:
            - "3306:3306"
        volumes:
            - "mysql_data:/data"

    phpmyadmin:
        image: "phpmyadmin/phpmyadmin"
        container_name: "phpmyadmin"
        links:
            - mysql:db
        environment:
            PMA_HOST: mysql
            MYSQL_USER: liuzt
            MYSQL_PASSWORD: 123qwe
            MYSQL_ROOT_PASSWORD: 123qwe
        ports:
            - "9090:80"
        depends_on:
            - mysql

volumes:
    mongodb_data:
    redis_data:
    mysql_data:
  
